### ISSUE TITLE
resolve.root support

### ISSUE THREAD

**Issue by a-s-o** [d4rkr00t/aik#118]
Hello,

Great package. I am really enjoying this package and you have made some really sensible decisions here. Thank you very much for your work.

I have one request if it is possible to add which is support for module root path support to get rid of `../../` in requires. For example if I have directory structure like like:
```
src/ 
  - utils/
    - LogWriter.js
  - components/
    - Something.js
```
I would like to import like this:
```
import Something from 'components/Something'
import LogWriter from 'utils/LogWriter'
```
So I believe there are two ways to accomplish this with webpack:

1. Use `resolve.root` or `resolve.moduleDirectories` options  (easier) - `aik` would just need to add a flag to the cli, such as `context` or `resolveRoot` or `baseUrl` and then provide that path to the webpack config
2. Use resolve.alias - Allow aliases to be defined in a config file or allowing multiple alias flags in the CLI

My preference is option 1 as it is simpler. this is the approach used by typescript with its baseUrl option and it works out really well. Option 2 is way more flexible but it needs more configuration and possibly a config file where aliases can be defined

Would you consider adding such a feature. I presume it is relatively easy and I can make a pull request if you don't have time. 

Thanks again.

**Comment by d4rkr00t** [comment]
Hi, 

Thanks for feedback. I'm glad that you found Aik useful. 

Adding this feature sounds reasonable. I like option 1 more than 2, because we should not lose ability to run aik without any config files.

However I hesitate a bit about adding extra flags. 

What do you think about using base path as module root? For example:

You run:

``` sh
aik index.js
```

Index.js is inside some folder, for example: "/Users/a-s-o/project/src/index.js"

We can use "/Users/a-s-o/project/src/" as a module root, always, without any options.

If it solves your case that's great. But anyway I'll plan it for next release and will investigate further. But it'd be better to avoid extra options where we can.

**Comment by a-s-o** [comment]
Yes, that would work just fine for me for all the cases I can recall.
Thanks.

**Comment by d4rkr00t** [comment]
PRs are welcome though. :)

But if you don't have time I'll do it myself for the next release.

**Comment by a-s-o** [comment]
Sure if I can figure it out I will make the PR.

**Comment by d4rkr00t** [comment]
Thanks.

**Comment by a-s-o** [comment]
Thanks for your help, Also I saw my name on the readme; wasn't necessary but much appreciated.

**Comment by d4rkr00t** [comment]
Thank you for your effort. And readme it's only way I can show how i appreciate your work and time. So I think it's important to add contributors to readme. 

Thanks again :)
